[package]
authors = ["Robin <robin.stoehr@code.berlin>"]
edition = "2018"
name = "raytracing_in_one_week"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rayon = "1.1"
